### ISSUE TITLE
Adding the Corresponding Ado2 and ADAPTING IDs as fields in NiDB

### ISSUE THREAD

**Issue by craigmoodie** [gbook/nidb#30]
Hi Greg,

I would like to submit the following enhancement requests to NiDB:

[1]

To avoid confusion in the future, is it possible to add the internal ado2 and project IDs (e.g. 4237) as additional fields that can be viewed and downloaded in the file name / as metadata? This would mean that when someone searches for or downloads data a subject's data based on the Olin NiBD external project ID, the metadata would also include fields that showed the corresponding internal MRI ID, as well as the ADAPTING ID used by JB and the folks collecting the clinical and cognitive data at HH. This is important for matching data across external data pulls, internal MRI data logs and the logs of out-of-scanner testing at HH. I'm not sure if all the other projects have all three ID designations, but if they could be added for the AA Connectivity project, that would be extremely helpful.

[2] 

Similarly, it would be good to easily tell if subject data had already been downloaded. Having a field that showed the date of last download or that indicated the data had not been downloaded would greatly enhance the efficiency of the manual curation of these data pull downs. If such a tag was included at the subject data set and individual MRI series level, that would be most advantageous.

Thanks!
-Craig.

**Comment by gbook** [comment]
Craig,
Thanks for the suggestions, and thanks for being patient with this whole process. NiDB was originally designed to be cross-project, with project specific IDs an after-thought. But users are needing project-specific functionality, so NiDB needs to adapt.

1) There is an option within each subject (on the Subject's page, if you edit their information) to include IDs for each project they are enrolled in. Putting an asterisk next to an ID makes it the primary ID for that project. For your example, a subject may have ID 4237 in the AA connectivity project, but ID S1234ABC for another project. So, I can make it simpler on the search page. Maybe when a particular project is selected on the search page, only the IDs associated with that project are displayed and used for downloading, etc. So if you select the AA connectivity project, only the primary IDs associated with that project are displayed on the search results and used for creating directories. Unfortunately for now, that ID information will need to be checked. The person at Olin sending the data will need to make sure all of the ID associations are  correct on the server.

2) I can put an indicator on series that have already been download in the search results. I don't want to hide previously downloaded series from search results because that may cause confusion for some users. But a previously downloaded indicator should help.

-G

**Comment by gbook** [comment]
This is mostly fixed. I'm marking it as closed for now. We can reopen it if we need to.
